name: main

on:
    push:
        branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    test:
        name: Test Suite
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Run test suite
              run: pnpm run test

    version_or_publish:
        name: Version or publish package
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Use Node LTS
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Creating .npmrc
              run: |
                  cat << EOF > "$HOME/.npmrc"
                    //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
                    //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  EOF
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Version or publish package
              id: changesets
              uses: changesets/action@v1
              with:
                  title: Release package
                  publish: pnpm run release
                  createGithubReleases: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
