name: main

on:
    push:
        branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    test:
        name: Test Suite
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Run test suite
              run: pnpm run test

    publish_to_npm:
        name: Publish to npm registry (if necessary)
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Use Node LTS
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm run publish:npm
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish_to_github:
        name: Publish to Github registry (if necessary)
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Use Node LTS
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Publish to Github
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm run publish:github
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
