name: Pre-merge

on:
    pull_request:
        branches: [main]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node LTS
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Build package
              run: pnpm run build

    test:
        name: Test Suite
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [lts/*, lts/-1, current]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Run test suite
              run: pnpm run test

    # Automatically create a changeset for dependabot
    # See: https://github.com/feelepxyz/dependabot-changesets
    changesets:
        name: Add changeset for dependabot
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        steps:
            - uses: mscharley/dependency-changesets-action@v1.0.6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
