name: Pre-merge

on:
    pull_request_target:
        types: [opened, synchronize, reopened]
        branches: [main]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node LTS
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Build package
              run: pnpm run build

    test:
        name: Test Suite
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [lts/*, lts/-1, current]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Run test suite
              run: pnpm run test

    # Create changesets (if necessary) and auto-merge pull requests from dependabot.
    dependabot:
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        needs: [build, test]
        steps:
            - uses: mscharley/dependency-changesets-action@v1.0.6
              with:
                  token: ${{ secrets.DEPENDENCY_UPDATE_GITHUB_TOKEN }}

            ##
            # Retry to work around "Base branch was modified" error.
            # See: https://github.com/cli/cli/issues/8092#issuecomment-1743904069
            ##
            - run: |
                  for i in {1..3}; do
                    if gh pr merge --auto --squash "${PR_URL}"; then
                      break
                    fi

                    if [[ $i -eq 3 ]]; then
                      exit 1
                    fi
                    sleep 5
                  done
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
