name: Release

env:
    node_versions: [16.x, 18.x, 20.x]
    node_lts: 20.x

on:
    push:
        branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: $node_versions

        steps:
            - uses: actions/checkout@v2
            - name: Use node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Run test suite
              run: pnpm run test

    release:
        name: Release
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Use node $node_lts
              uses: actions/setup-node@v3
              with:
                  node-version: $node_lts

            - name: Install dependencies
              run: corepack enable && pnpm install --frozen-lockfile

            - name: Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
